# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[llvm]
optimize = true
release-debuginfo = false
download-ci-llvm = false
thin-lto = true
cxxflags = "-march=native"
cflags = "-march=native"

[rust]
debug = false
parallel-compiler = true
channel = "nightly"
jemalloc = true
codegen-units = 1
codegen-units-std = 1

[target.x86_64-unknown-linux-gnu]
sanitizers = true

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin20.4-clang"
ar = "x86_64-apple-darwin20.4-ar"
