# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[llvm]
optimize = true
release-debuginfo = false
download-ci-llvm = false

[rust]
debug = false

[build]
sanitizers = true

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin20.4-clang"
ar = "x86_64-apple-darwin20.4-ar"
